=== tomit4/city_stats/research/states_schema.min.json
{"$schema":"http://json-schema.org/draft-07/schema#","type":"object","required":["name","date_admitted","capital","largest_city","govenor","senators","house_delegation","area","elevation","population","time_zone","latitude","longitude","url","flag_url","insignia_url"],"properties":{"name":{"type":"string"},"date_admitted":{"type":"string"},"capital":{"type":"string"},"largest_city":{"title":"Largest_city","type":"string"},"govenor":{"title":"Govenor","type":"string"},"senators":{"type":"array","representatives":{"type":"string"}},"house_delegation":{"type":"array","representatives":{"type":"string"}},"area":{"type":"object","area_stats":{"type":"string"}},"elevation":{"type":"string","elevation_stats":{"type":"string"}},"population":{"type":"object","items":{"type":"string"}},"time_zone":{"type":"string"},"latitude":{"type":"string"},"longitude":{"type":"string"},"url":{"type":"string"},"flag_url":{"type":"string"},"insignia_url":{"type":"string"}}}

=== tomit4/city_stats/research/states_alabama.json
{
  "name": "Alabama",
  "date_admitted": "1819-12-14T00:00:00.000Z",
  "capital": "Montgomery",
  "largest_city": "Huntsville",
  "govenor": "Kay Ivey",
  "senators": ["Tommy Tuberville", "Katie Britt"],
  "house_delegation": [
    "Jerry Carl",
    "Barry Moore",
    "Mike Rogers",
    "Robert Aderholt",
    "Dale Strong",
    "Gary Palmer",
    "Terri Sewell"
  ],
  "area": {
    "total": "52419 sq mi",
    "land": "50744 sq mi",
    "water": "1675 sq mi"
  },
  "elevation": "500 ft",
  "population": {
    "total": "5039877",
    "density": "99.1/sq mi",
    "median_household_income": "$52000"
  },
  "time_zone": "UTC-06:00(Central)",
  "latitude": "30째11' N to 35째 N",
  "longitude": "84째53' W to 88째28' W",
  "url": "https://www.alabama.gov/",
  "flag_url": "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Alabama.svg",
  "insignia_url": "https://upload.wikimedia.org/wikipedia/commons/f/f7/Seal_of_Alabama.svg"
}
